goog.provide("TestApplication.Constants");

/**
 * @enum {number}
 */
TestApplication.Constants = {
    CANVAS_WIDTH: 640,
    CANVAS_HEIGHT: 480,
    TOOLBAR_HEIGHT: 30,
    SHAPE_START_WIDTH: 100,
    SHAPE_START_HEIGHT: 100,
    SHAPE_START_POSITION_X: 270 ,
    SHAPE_START_POSITION_Y: 190,
    RESIZE_POINT_WIDTH: 10,
    RESIZE_POINT_HEIGHT: 10,
    RESIZE_POINT_RADIUS: 5,
    MIN_SHAPE_WIDTH: 30,
    MAX_SHAPE_WIDTH: 300,
    MIN_SHAPE_HEIGHT: 30,
    MAX_SHAPE_HEIGHT: 300
};